name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.26
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_db
        ports: 
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ibkkamura/rese-docker-test

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./docker/php
        file: ./docker/php/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Run Docker container
      run: docker run -d --name laravel-app --network host -v ${{ github.workspase }}/src:/var/www ${{ steps.meta.outputs.tags }}

    - name: Install Composer dependencies
      run: |
        docker exec laravel-app composer install
        --working-dir=/var/www
        --no-interaction --prefer-dist
        --optimize-autoloader

    - name: Run migrations
      run: docker exec laravel-app php /var/www/ artisan migrate
    
    - name: Run tests
      run: docker exec laravel-app php /var/www/ artisan test
