name: Docker Test CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker
        run: docker-compose up -d --build

      - name: Composer Install
        run: |
          docker-compose exec php bash
          composer install
          exit

      - name: Setup env
        run: |
          docker-compose exec php bash
          cp .env.example .env
          php artisan key:generate
          exit
        env: |
          DB_CONNECTION=mysql
          DB_HOST=mysql
          DB_DATABASE=laravel_db
          DB_USERNAME=laravel_user
          DB_PASSWORD=laravel_pass

      - name: Run migrations
        run: |
          docker exec php bash
          php artisan migrate

      - name: Run tests
        run: |
          docker exec php bash
          php artisan test
